### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by juanlatorre** [lamsfoundation/lams#1]
Hi, I worked the whole 2017 with LAMS 2.5, a friend told me about LAMS 3.0 and I tought, hey, the feature list looks really impresive, so I tried to compile the source code from the lams31 branch, but I don't know where to start.

Someone has a simple compilation instruction and how to deploy?

Thanks in advance.

**Comment by MarcinCieslak** [comment]
Hi Juan,
there is a manual. Even though it is a bit outdated, it can give you a general idea what to do.
https://wiki.lamsfoundation.org/display/lams/Building+LAMS
https://wiki.lamsfoundation.org/display/lamsdocs/Installing+MySQL+on+Windows+for+LAMS

It goes more or less like this:
1. Get latest Eclipse. Get JBoss tools plugin if you want to operate WildFly from within Eclipse
2. Get WildFly 8,2.1
3. Get MySQL 5.7
4. Create a DB as describe in the link above. Use utf8mb4 character set.
5. Get LAMS code from master branch. The branch "lams31" is for LAMS 3.1 and contains experimental code.
6. Go through lams_build/*.properties file. If you want to overwrite any setting, put it into lams_build/build.properties. It takes precedence over other .properties files and and is ignored by git.
7. Run lams-cruise Ant target from lams_build/build.xml
8. Start WildFly

Give it a go and let us know if you run into trouble. We will try to help.

**Comment by danielkschneider** [comment]
Hello, I decided to have a go again at LAMS. Tried to install it and ran into problems. LAMS seems to build fine but then would fail to deploy. Maybe it's just a permission error. I am doing this as a normal user. Both LAMS and Wildfly files belong to me.

System = Ubuntu 18LTS, OpenJDK 8, MySQL 5.7x
I attached a file with logs. Great, if you could help me
[logs-ubuntu.zip](https://github.com/lamsfoundation/lams/files/2567358/logs-ubuntu.zip)

btw. I wrote down somewhat what I did: 
https://edutechwiki.unige.ch/en/LAMS_installation_and_configuration#LAMS_3.0

- greetings ! Daniel
PS: If Ernie is listening in. Do you still use the translation server ? If yes, I will pick up the french version again if I can get this running.

**Comment by juanlatorre** [comment]
Hi, I will try to reproduce every step in order to test it, after that I will message you, sorry for the poor english, and thank you !

**Comment by danielkschneider** [comment]
Thanx cool :) Alternatively you also could provide some more detailed instructions. e.g. what Java to use and also confirm that we have to use Wildfly 8.2.x, that we should use the master version, etc.

**Comment by erniegx** [comment]
Hi Daniel,

Good to hear from you again. 

>   PS: If Ernie is listening in. Do you still use the translation server ? If yes, I will pick up the french version again if I can get this running.

Yes, we still use the [translations server](https://translations.lamsinternational.com/lams/). About 2 weeks ago, I upgraded it to our latest LAMS 3.1 -which we are still testing but should be out at the end of December 2018. 

Once again, thanks for the details instructions on [building LAMS 3.0 in Ubuntu](https://edutechwiki.unige.ch/en/LAMS_installation_and_configuration#LAMS_3.0). 

I've just created a page on  [Building LAMS 3.1](https://wiki.lamsfoundation.org/display/lams/Building+LAMS+3.1) in case you are interested. It's pretty much the same steps as 3.0, but just all newer tech stack. However, a more detailed version like your about LAMS 3.0 in Ubuntu is probably easier. Will work on that. 

Now, looking at your logs, I think I've seen what the issue is. See if in your `wildfly-8.2.1/standalone/deployments/lams.ear/lams-www.war/META-INF/` folder, and if there's a services folder, please delete it and try restart Wildfly again. 

Let me know if that works alright. 

Thanks,

Ernie

**Comment by erniegx** [comment]
Daniel, Juan, 

Take a look at this [Quick compile guide in Ubuntu for LAMS 3.1](https://wiki.lamsfoundation.org/display/lams/LAMS+3.1+in+Ubuntu). 

Comments welcome.

**Comment by danielkschneider** [comment]
Hi Ernie, good to see you too :)

> Now, looking at your logs, I think I've seen what the issue is. See if in your `wildfly-8.2.1/standalone/deployments/lams.ear/lams-www.war/META-INF/` folder, and if there's a services folder, please delete it and try restart Wildfly again.
> 

No that is not the problem. In this directory there is only a file called MANIFEST.MF
 $ ls -la standalone/deployments/lams.ear/lams-www.war/META-INF/
 -rw-r--r-- 1 schneide tecfa  260 Nov  9 20:33 MANIFEST.MF

The only services directory in deployments is the following. Killing it did not help ;)
 find . -name services -ls
 16129160      4 drwxr-xr-x   2 schneide tecfa        4096 Nov  9 20:33 ./standalone/deployments/lams.ear/lams-central.war/META-INF/services

I also will try installing LAMS 3.1. If it sort of works I rather play with that since it will be the future.

**Comment by juanlatorre** [comment]
Thanks for all the comments, finally made it with the instructions provided by @erniegx
