### ISSUE TITLE
Why "CKEditor insert video media" can not support oEmbed?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#15]
Youtube is blocked in China. Instead I setup an internal Peertube, which supports oEmbed protocal, i.e.  https://peertube.cpy.re/w/sWxgbBUu1ScQkHqz831Qqi There is the "type="application/json+oembed"" in the HTML source.

But in LAMS ckeditor authoring page, it cannot show up:
![image](https://user-images.githubusercontent.com/1741341/129119432-85697f72-e283-4d8e-952f-c2fae8a6cfe9.png)
And in the preview page, it can only show the poster image, no controls to play the video:
![image](https://user-images.githubusercontent.com/1741341/129120349-7f8fe8b7-f924-47b7-bd80-d4d485dfb3d0.png)

CKEditor indeedly supports oEmbed with this addon: https://ckeditor.com/cke4/addon/oembed

**Comment by MarcinCieslak** [comment]
Maybe we will include oEmbed plugin in future LAMS releases. It is not a priority now, though.
You can try to include it yourself for you instance. CKEditor code is in /lams_central/web/ckeditor
Please take a look at our edited README.md there. I suggest you try to include the plugin with the existing LAMS code rather than try to build latest CKEditor with that plugin included and then apply LAMS customisations - it can prove being pretty tricky.
If you are successful and want to share it, please create a pull request to our public LAMS repository :)

**Comment by fishfree** [comment]
@MarcinCieslak Thank you for your tip. I manually installed the CKEditor oEmbed addon, it still didn't work. Could you please have a look at the iframe.ly debug page: http://debug.iframely.com/?uri=https%3A%2F%2Fpeertube.cpy.re%2Fw%2FsWxgbBUu1ScQkHqz831Qqi
Youtube works: http://debug.iframely.com/?uri=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhxLfH3TzGaA
It seems there is no player output in the former.

**Comment by MarcinCieslak** [comment]
LAMS in version 4.6 has oEmbed plugin installed. It has no LAMS customisations applied. Should it not work, it is probably the plugin or CKEditor issue.
