### ISSUE TITLE
How to upgrade ( recompile) LAMS 4.x and keeping existing data  in a production environment?

### ISSUE THREAD

**Issue by fishfree** [lamsfoundation/lams#24]
I searched no related documentation about this.

**Comment by MarcinCieslak** [comment]
Hi!
What you need to do is to recompile LAMS on separate environment. Then you need to deliver the new lams.ear to production. You probably want to backup the existing lams.ear and after upgrade copy back its lams-www.war/public and lams-www.war/secure folders as this is where users' files are stored.
Also check if in code lams_build/conf/standalone.xml has changed since the last time you upgraded. If so, you need to apply those changes manually to standalone.xml at the server.

**Comment by fishfree** [comment]
@MarcinCieslak Thank you very much! If there are some changes in the database table schema after upgrading, will the old data upgrade automatically?

**Comment by MarcinCieslak** [comment]
Yes. We use a mechanism called Autopatch to perform incremental DB patches on code upgrade.
